POST https://api-yinying-ng.wingmark.cn/v1/chatWithCyberFurry
Content-Type: application/json
Authorization: Bearer yinying-2L8NvWk82J6urz85dree23e6aesOCfOnQUo6M7ojggty

//{
//  "appId":"testdebug",
//  "chatId":"appId-用户标识符-随机字符", //lanhuobot
//  "model":"yinyingllm-v2",
//  "variables": {
//    "nickName":"昵称",
//    "furryCharacter":"设定",
//    "promptPatch":"可以在这里对银影进行提示，例如自定义知识库、自定义对话规则和内容" // only for yinying
//  },
//  "systemPrompt":"你的名字叫银影，是翎迹网络开发的仿生灰狼", // only for cyberfurry001
//  "message":"对话信息"
//  "multimodal":"图片 url"
//}

{
  "appId":"lanhuobot",
  "chatId":"lanhuobot-testmany-1",
  "variables": {
    "nickName":"没有哦",
    "furryCharacter":"没有哦",
    "promptPatch":"你在和一群人对话,每个人以 [name] 前缀区分"
  },
  "model":"yinyingllm-latest",
  "systemPrompt":"你的名字叫银影，是翎迹网络开发的仿生灰狼",
  "message":"[bulefire]:咱要贴贴qwq"
}